import { SanctionedRecord, ImportJob, DashboardStats } from '../types';

export const mockRecords: SanctionedRecord[] = [
  {
    id: 1,
    referenceNumber: 'REG-2020-001',
    recordType: 'INDIVIDUAL',
    primaryName: 'John Alexander Smith',
    listingDate: '2020-08-20',
    lastUpdate: '2024-01-15',
    firstImported: '2024-01-01',
    lastSynchronized: '2024-12-01T10:30:00Z',
    sourceStatus: 'ACTIVE',
    sourceUrl: 'https://main.un.org/securitycouncil/en/content/un-sc-consolidated-list',
    aliases: [
      { id: 101, aliasName: 'J. A. Smith', quality: 'good', originalRepresentation: null },
      { id: 102, aliasName: 'Johnny Smith', quality: 'good', originalRepresentation: null },
      { id: 103, aliasName: 'John Smith', quality: null, originalRepresentation: null },
    ],
    biographicalDetails: [{
      dateOfBirth: '1960-04-07',
      datePrecision: 'EXACT',
      placeOfBirth: 'London',
      nationality: 'British',
      gender: 'M',
      identificationDocuments: [{ type: 'Passport', number: 'D00012345', issuingCountry: 'UK', issueDate: null, expiryDate: null }],
      addresses: ['London, UK'],
    }],
    sanctionsPrograms: [{ program: 'Program Alpha', referenceInfo: 'Financial regulations', listingDetails: 'Designated pursuant to resolution provisions' }],
  },
  {
    id: 2,
    referenceNumber: 'REG-2009-037',
    recordType: 'INDIVIDUAL',
    primaryName: 'Maria Elena Rodriguez',
    listingDate: '2009-03-04',
    lastUpdate: '2023-06-10',
    firstImported: '2024-01-01',
    lastSynchronized: '2024-12-01T10:30:00Z',
    sourceStatus: 'ACTIVE',
    sourceUrl: 'https://main.un.org/securitycouncil/en/content/un-sc-consolidated-list',
    aliases: [
      { id: 201, aliasName: 'Maria Rodriguez', quality: 'good', originalRepresentation: null },
      { id: 202, aliasName: 'M. E. Rodriguez', quality: null, originalRepresentation: null },
      { id: 203, aliasName: 'Elena Rodriguez', quality: null, originalRepresentation: null },
    ],
    biographicalDetails: [{
      dateOfBirth: '1975-06-15',
      datePrecision: 'EXACT',
      placeOfBirth: 'Madrid',
      nationality: 'Spanish',
      gender: 'F',
      identificationDocuments: [],
      addresses: ['Madrid, Spain'],
    }],
    sanctionsPrograms: [{ program: 'Program Beta', referenceInfo: 'Trade compliance', listingDetails: 'Listed for regulatory violations' }],
  },
  {
    id: 3,
    referenceNumber: 'REG-2011-003',
    recordType: 'INDIVIDUAL',
    primaryName: 'Chen Wei Zhang',
    listingDate: '2011-02-26',
    lastUpdate: '2023-11-20',
    firstImported: '2024-01-01',
    lastSynchronized: '2024-12-01T10:30:00Z',
    sourceStatus: 'ACTIVE',
    sourceUrl: 'https://main.un.org/securitycouncil/en/content/un-sc-consolidated-list',
    aliases: [
      { id: 301, aliasName: 'Wei Zhang', quality: 'good', originalRepresentation: null },
      { id: 302, aliasName: 'Chen Zhang', quality: null, originalRepresentation: null },
      { id: 303, aliasName: 'Zhang Wei', quality: null, originalRepresentation: null },
    ],
    biographicalDetails: [{
      dateOfBirth: '1968-09-22',
      datePrecision: 'EXACT',
      placeOfBirth: 'Beijing',
      nationality: 'Chinese',
      gender: 'M',
      identificationDocuments: [],
      addresses: ['Beijing'],
    }],
    sanctionsPrograms: [{ program: 'Program Gamma', referenceInfo: 'Technology export', listingDetails: 'Designated pursuant to resolution provisions' }],
  },
  {
    id: 4,
    referenceNumber: 'REG-2020-005',
    recordType: 'ENTITY',
    primaryName: 'Global Trading Corporation',
    listingDate: '2020-08-20',
    lastUpdate: '2024-03-01',
    firstImported: '2024-01-01',
    lastSynchronized: '2024-12-01T10:30:00Z',
    sourceStatus: 'ACTIVE',
    sourceUrl: 'https://main.un.org/securitycouncil/en/content/un-sc-consolidated-list',
    aliases: [
      { id: 401, aliasName: 'GTC', quality: 'good', originalRepresentation: null },
      { id: 402, aliasName: 'Global Trading Corp', quality: null, originalRepresentation: null },
    ],
    biographicalDetails: [{
      dateOfBirth: null, datePrecision: null, placeOfBirth: null, nationality: null, gender: null,
      identificationDocuments: [],
      addresses: ['Singapore'],
    }],
    sanctionsPrograms: [{ program: 'Program Alpha', referenceInfo: 'Financial regulations', listingDetails: 'Designated pursuant to resolution provisions' }],
  },
  {
    id: 5,
    referenceNumber: 'REG-2007-042',
    recordType: 'INDIVIDUAL',
    primaryName: 'Ahmed Hassan Ibrahim',
    listingDate: '2007-04-27',
    lastUpdate: '2023-09-15',
    firstImported: '2024-01-01',
    lastSynchronized: '2024-12-01T10:30:00Z',
    sourceStatus: 'ACTIVE',
    sourceUrl: 'https://main.un.org/securitycouncil/en/content/un-sc-consolidated-list',
    aliases: [
      { id: 501, aliasName: 'Ahmad Hassan Ibrahim', quality: 'good', originalRepresentation: null },
      { id: 502, aliasName: 'Ahmed Ibrahim', quality: null, originalRepresentation: null },
      { id: 503, aliasName: 'A. H. Ibrahim', quality: null, originalRepresentation: null },
    ],
    biographicalDetails: [{
      dateOfBirth: '1964-12-12',
      datePrecision: 'EXACT',
      placeOfBirth: 'Cairo',
      nationality: 'Egyptian',
      gender: 'M',
      identificationDocuments: [],
      addresses: ['Cairo'],
    }],
    sanctionsPrograms: [{ program: 'Program Beta', referenceInfo: 'Trade compliance', listingDetails: 'Listed for regulatory violations' }],
  },
  {
    id: 6,
    referenceNumber: 'REG-2010-001',
    recordType: 'INDIVIDUAL',
    primaryName: 'Viktor Petrov',
    listingDate: '2010-04-12',
    lastUpdate: '2023-08-01',
    firstImported: '2024-01-01',
    lastSynchronized: '2024-12-01T10:30:00Z',
    sourceStatus: 'ACTIVE',
    sourceUrl: 'https://main.un.org/securitycouncil/en/content/un-sc-consolidated-list',
    aliases: [
      { id: 601, aliasName: 'Viktor P.', quality: 'good', originalRepresentation: null },
      { id: 602, aliasName: 'Victor Petrov', quality: null, originalRepresentation: null },
    ],
    biographicalDetails: [{
      dateOfBirth: '1955-03-18',
      datePrecision: 'EXACT',
      placeOfBirth: 'Moscow',
      nationality: 'Russian',
      gender: 'M',
      identificationDocuments: [],
      addresses: ['Moscow'],
    }],
    sanctionsPrograms: [{ program: 'Program Delta', referenceInfo: 'Regional stability', listingDetails: 'Listed for obstructing diplomatic process' }],
  },
  {
    id: 7,
    referenceNumber: 'REG-2014-001',
    recordType: 'INDIVIDUAL',
    primaryName: 'Pierre Dubois',
    listingDate: '2014-12-18',
    lastUpdate: '2023-10-05',
    firstImported: '2024-01-01',
    lastSynchronized: '2024-12-01T10:30:00Z',
    sourceStatus: 'ACTIVE',
    sourceUrl: 'https://main.un.org/securitycouncil/en/content/un-sc-consolidated-list',
    aliases: [
      { id: 701, aliasName: 'Pierre J. Dubois', quality: 'good', originalRepresentation: null },
      { id: 702, aliasName: 'P. Dubois', quality: null, originalRepresentation: null },
    ],
    biographicalDetails: [{
      dateOfBirth: '1970-07-14',
      datePrecision: 'EXACT',
      placeOfBirth: 'Paris',
      nationality: 'French',
      gender: 'M',
      identificationDocuments: [],
      addresses: ['Paris, France'],
    }],
    sanctionsPrograms: [{ program: 'Program Epsilon', referenceInfo: 'Humanitarian affairs', listingDetails: 'Listed for actions undermining stability' }],
  },
  {
    id: 8,
    referenceNumber: 'REG-2011-101',
    recordType: 'ENTITY',
    primaryName: 'National Investment Fund',
    listingDate: '2011-03-03',
    lastUpdate: '2024-02-15',
    firstImported: '2024-01-01',
    lastSynchronized: '2024-12-01T10:30:00Z',
    sourceStatus: 'ACTIVE',
    sourceUrl: 'https://main.un.org/securitycouncil/en/content/un-sc-consolidated-list',
    aliases: [
      { id: 801, aliasName: 'NIF', quality: 'good', originalRepresentation: null },
    ],
    biographicalDetails: [{
      dateOfBirth: null, datePrecision: null, placeOfBirth: null, nationality: null, gender: null,
      identificationDocuments: [],
      addresses: ['Tripoli'],
    }],
    sanctionsPrograms: [{ program: 'Program Gamma', referenceInfo: 'Technology export', listingDetails: 'Assets frozen pursuant to resolution provisions' }],
  },
  {
    id: 9,
    referenceNumber: 'REG-2024-001',
    recordType: 'INDIVIDUAL',
    primaryName: 'Abdul Rahman Al-Said',
    listingDate: '2024-01-15',
    lastUpdate: '2024-01-15',
    firstImported: '2024-01-20',
    lastSynchronized: '2024-12-01T10:30:00Z',
    sourceStatus: 'ACTIVE',
    sourceUrl: 'https://main.un.org/securitycouncil/en/content/un-sc-consolidated-list',
    aliases: [
      { id: 901, aliasName: 'Abdulrahman Al-Said', quality: 'good', originalRepresentation: null },
      { id: 902, aliasName: 'Abd Al-Rahman Al-Sayeed', quality: null, originalRepresentation: null },
      { id: 903, aliasName: 'A. Rahman Al-Said', quality: null, originalRepresentation: null },
    ],
    biographicalDetails: [{
      dateOfBirth: '1979-01-01',
      datePrecision: 'YEAR_ONLY',
      placeOfBirth: 'Sanaa',
      nationality: 'Yemeni',
      gender: 'M',
      identificationDocuments: [],
      addresses: ['Yemen'],
    }],
    sanctionsPrograms: [{ program: 'Program Zeta', referenceInfo: 'Regional affairs', listingDetails: 'Listed for actions undermining peace' }],
  },
  {
    id: 10,
    referenceNumber: 'REG-2023-003',
    recordType: 'INDIVIDUAL',
    primaryName: 'Kofi Mensah',
    listingDate: '2023-05-10',
    lastUpdate: '2023-11-01',
    firstImported: '2024-01-01',
    lastSynchronized: '2024-12-01T10:30:00Z',
    sourceStatus: 'ACTIVE',
    sourceUrl: 'https://main.un.org/securitycouncil/en/content/un-sc-consolidated-list',
    aliases: [
      { id: 1001, aliasName: 'Kofi A. Mensah', quality: 'good', originalRepresentation: null },
      { id: 1002, aliasName: 'K. Mensah', quality: null, originalRepresentation: null },
    ],
    biographicalDetails: [{
      dateOfBirth: '1956-12-20',
      datePrecision: 'EXACT',
      placeOfBirth: 'Accra',
      nationality: 'Ghanaian',
      gender: 'M',
      identificationDocuments: [],
      addresses: ['Accra'],
    }],
    sanctionsPrograms: [{ program: 'Program Eta', referenceInfo: 'Resource management', listingDetails: 'Designated for supporting unauthorized activities' }],
  },
  {
    id: 11,
    referenceNumber: 'REG-2020-015',
    recordType: 'INDIVIDUAL',
    primaryName: 'Yuki Tanaka',
    listingDate: '2020-08-20',
    lastUpdate: '2024-01-15',
    firstImported: '2024-01-01',
    lastSynchronized: '2024-12-01T10:30:00Z',
    sourceStatus: 'ACTIVE',
    sourceUrl: 'https://main.un.org/securitycouncil/en/content/un-sc-consolidated-list',
    aliases: [
      { id: 1101, aliasName: 'Y. Tanaka', quality: 'good', originalRepresentation: null },
      { id: 1102, aliasName: 'Tanaka Yuki', quality: null, originalRepresentation: null },
    ],
    biographicalDetails: [{
      dateOfBirth: '1982-05-30',
      datePrecision: 'EXACT',
      placeOfBirth: 'Tokyo',
      nationality: 'Japanese',
      gender: 'F',
      identificationDocuments: [],
      addresses: ['Tokyo'],
    }],
    sanctionsPrograms: [{ program: 'Program Alpha', referenceInfo: 'Financial regulations', listingDetails: 'Designated for financial activities' }],
  },
  {
    id: 12,
    referenceNumber: 'REG-2008-101',
    recordType: 'ENTITY',
    primaryName: 'Pacific Shipping Ltd',
    listingDate: '2008-04-12',
    lastUpdate: '2024-02-01',
    firstImported: '2024-01-01',
    lastSynchronized: '2024-12-01T10:30:00Z',
    sourceStatus: 'ACTIVE',
    sourceUrl: 'https://main.un.org/securitycouncil/en/content/un-sc-consolidated-list',
    aliases: [
      { id: 1201, aliasName: 'PSL', quality: 'good', originalRepresentation: null },
      { id: 1202, aliasName: 'Pacific Shipping', quality: null, originalRepresentation: null },
    ],
    biographicalDetails: [{
      dateOfBirth: null, datePrecision: null, placeOfBirth: null, nationality: null, gender: null,
      identificationDocuments: [],
      addresses: ['Singapore'],
    }],
    sanctionsPrograms: [{ program: 'Program Delta', referenceInfo: 'Regional stability', listingDetails: 'Listed as organization threatening stability' }],
  },
];

export const mockImportJobs: ImportJob[] = [
  {
    id: 1,
    startTime: '2024-12-01T10:00:00Z',
    completionTime: '2024-12-01T10:30:00Z',
    status: 'COMPLETED',
    recordsCreated: 0,
    recordsUpdated: 12,
    recordsRemoved: 0,
    failures: 0,
    errorSummary: null,
    sourceUrl: 'https://main.un.org/securitycouncil/en/content/un-sc-consolidated-list',
  },
  {
    id: 2,
    startTime: '2024-11-15T08:00:00Z',
    completionTime: '2024-11-15T08:25:00Z',
    status: 'COMPLETED',
    recordsCreated: 2,
    recordsUpdated: 10,
    recordsRemoved: 0,
    failures: 0,
    errorSummary: null,
    sourceUrl: 'https://main.un.org/securitycouncil/en/content/un-sc-consolidated-list',
  },
  {
    id: 3,
    startTime: '2024-11-01T06:00:00Z',
    completionTime: '2024-11-01T06:15:00Z',
    status: 'FAILED',
    recordsCreated: 0,
    recordsUpdated: 0,
    recordsRemoved: 0,
    failures: 1,
    errorSummary: 'Network timeout: Connection timed out after 30 seconds',
    sourceUrl: 'https://main.un.org/securitycouncil/en/content/un-sc-consolidated-list',
  },
];

export const mockDashboardStats: DashboardStats = {
  totalIndividuals: 520,
  totalEntities: 380,
  lastSyncTime: '2024-12-01T10:30:00Z',
  lastSyncStatus: 'SUCCESS',
  recentFailures: [mockImportJobs[2]],
  ollamaAvailable: true,
  ollamaModel: 'qwen3:4b',
  dataFreshness: '2024-12-01',
  totalRecords: 900,
};
